// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNGk4nK-Q6DkcjTEo0he0RyccX9PNvAB8',
    appId: '1:634058054839:android:05981a81ab4161af5fc132',
    messagingSenderId: '634058054839',
    projectId: 'device-e15f3',
    storageBucket: 'device-e15f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4775FCLVnVFzfA5oAGZ3wCEhQb7MOBTQ',
    appId: '1:634058054839:ios:f8ddd8d5b51c935e5fc132',
    messagingSenderId: '634058054839',
    projectId: 'device-e15f3',
    storageBucket: 'device-e15f3.appspot.com',
    iosBundleId: 'com.example.recsan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4775FCLVnVFzfA5oAGZ3wCEhQb7MOBTQ',
    appId: '1:634058054839:ios:f8ddd8d5b51c935e5fc132',
    messagingSenderId: '634058054839',
    projectId: 'device-e15f3',
    storageBucket: 'device-e15f3.appspot.com',
    iosBundleId: 'com.example.recsan',
  );
}
